# Generated by Django 3.0.3 on 2021-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiterName', models.CharField(max_length=100)),
                ('recruiterEmail', models.CharField(max_length=100)),
                ('jobDetails', models.CharField(max_length=1000)),
            ],
        ),
    ]
