# Generated by Django 3.2.6 on 2021-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210829_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
