# Generated by Django 3.2.6 on 2021-08-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210829_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
