# Generated by Django 3.2.6 on 2021-08-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210829_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
